### ISSUE TITLE
Question about bandwidth

### ISSUE THREAD

**Issue by JeffCarpenter** [plutoplus/plutoplus#13]
Hi there, I'm wondering what bandwidth this SDR supports. Is it roughly the same as the standard Pluto?

**Comment by SQ6RDP** [comment]
Pluto+ has a litle bug: cheap Balun B0310J50100AHF 300MHZ-1GHZ instead of TCM1-63AX 10MHZ-6GHz as in oryginal pluto

**Comment by SQ6RDP** [comment]
![pluto balun](https://user-images.githubusercontent.com/81185184/140978212-1d636f24-1cda-4380-bfed-0f1a1b7ee0f5.jpeg)

That's the Pluto plus balun - complete lack of sensitivity on the  144mhs band.

look how oryginal Adalm Pluto works:

https://www.youtube.com/watch?v=M-t0DqcSv4k

ADALM Pluto  balun:
![Adalm pluto - balun](https://user-images.githubusercontent.com/81185184/140979332-dc1503f9-df19-4928-8f56-b2f673292489.png)
 Pluto plus balun:

![pluto plus - balun](https://user-images.githubusercontent.com/81185184/140979450-79c8105d-3ec6-4d82-91fd-f78c1e4a6dd9.png)
