### ISSUE TITLE
Pluto Plus - No TX Output after v34plus upgrade

### ISSUE THREAD

**Issue by n3ua** [plutoplus/plutoplus#33]
After upgrading firmware to Ver34plus ( from http://tiger.dirlinger.at/plutoplus ) Could not get any output power  !
Can anybody suggest  what is the latest good working firmware  for Pluto Plus

Thanks

Sejo

**Comment by n3ua** [comment]
Firmware update to V0.35 fixed  the problem

**Comment by OE2WNL** [comment]
Hi!

where do I get v0.35 ?

Thank you very much!

**Comment by azolotko** [comment]
@OE2WNL I’ve published [a build based on v0.38](https://github.com/azolotko/plutoplus/releases/tag/v0.38). Give it a try.
